### ISSUE TITLE
ExporterClass: read data from model as well

### ISSUE THREAD

**Issue by julianstar88** [julianstar88/Aphrodite#1]
# Reason
It should be possible to read data also form a data model such as *QStandardItemModel*. The *Model/View framework* has been created to interact with data in a uniform way, independent from its source. By only reading data from the data source (database files), as it is in the ExporterClass, this principle gets violated.

# Roadmap
~~- [ ] create a getter/ setter method to a new property *dataModel*~~
~~- [ ] create a flag to decide in the *populateRoutine* method from which source to take its data~~
~~- [ ] implement Unittests for the getter and setter~~
~~- [ ] adapt the test for *populateRoutine* if this is required~~
~~- [ ] extend the docstring documentation in the ExporterClass~~

**Comment by julianstar88** [comment]
# update to Roadmap
the idea of a decision flag is obsolete. instead, a similar procedure to *GraphicalEvaluator* should be implemented. this means two methods for data retrieving are required. the new Roadmap would look like this:
- [ ] create getter/ setter methods for a new property called *dataModel*
- [ ] create the two methods: *dataFromModel* and *dataFromDatabase*
- [ ] implement Unittests for all new methods
- [ ] adapt the test for *populateRoutine* if this is required
- [ ] extend the docstring documentation if the ExporterClass
