### ISSUE TITLE
Data Model: commitToDatabase-method

### ISSUE THREAD

**Issue by julianstar88** [julianstar88/Aphrodite#2]
# Reason
since the user should only interact with the data model (e.g. the *CustomModel.CustomSqlModel*), it´s mandatory to notify the underlying database of changes in the data of the Model. This notification is at least necessary if different objects are about to retrieve data from the model.

# Roadmap
- [ ] introduce a method like *commitTableToDatabase* in the module: *CustomModel.CustomSqlModel*

An implementation could comprise the following steps:
- [ ] drop old table from a database
- [ ] compose a new table consisting of *QStandardItems* with updated data
- [ ] add the newly formed table to the above mentioned database

**Comment by julianstar88** [comment]
This method is obsolete. There is a much easier way to achieve the data transfer from the model to the database. Just use the Methods in the Database.database-class
