### ISSUE TITLE
MainModules.Database Module: remove libs 'os' and 'os.path'

### ISSUE THREAD

**Issue by julianstar88** [julianstar88/Aphrodite#4]
# Reason
To work with paths together with the libraries *os* and *os.path* is complicated because it´s necessary to mix up methods from both modules. There is a more elegant and object-oriented way to work with paths: *pathlib2*

# Roadmap
- [x] delete imports from *os* and *os.path*
- [x] delete *os* and *os.path* from *__checkPath* and replace it with *pathlib2*
- [x] delete *os.path* from *establishConnection* and replace it with *pathlib2*
