### ISSUE TITLE
Errorhandling in *GraphicalEvaluator*

### ISSUE THREAD

**Issue by julianstar88** [julianstar88/Aphrodite#8]
# Problem
*GraphicalEvaluator* shouldn't crash the program by raising an exception. Instead, the tabs within the evaluator should be empty. Maybe it´s possible to create a message on the status bar of Aphrodite, in a future version.

# Roadmap
the following methods are affected (at the `TODO`-marked lines):
- [x] *GraphicalEvaluator.createTabs* (1x `TODO`)
- [x] *GraphicalEvaluator.plotData* (2x `TODO`)

don´t forget to adapt the unittest (*GraphicalEvaluator.plotData* does not have any tests)
- [x] *test_GraphicalEvaluator.EvaluatorLayout.test_createTabs*
